### ISSUE TITLE
"produksjonslinjer", og regneark for alle bøker i hver av dem

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#185]
God ide fra @usama49: lage oversikt over bøker og produksjonslinjer som regneark.

Vi må definere "produksjonslinjer" et sted. Kanskje i en egen yaml-fil, eventuelt bare rett i produksjonssystem.yaml.

For eksempel:

```yaml
production-lines:
    "e-bok":
        # pipeline uid : ansvarlig
        - incoming-nordic: Fornavn.Etternavn@nlb.no
        - nordic-epub-to-nlbpub: Fornavn.Etternavn@nlb.no
        - insert-metadata-xhtml: Fornavn.Etternavn@nlb.no
        - prepare-for-ebook: Fornavn.Etternavn@nlb.no
        - nlbpub-to-html: Fornavn.Etternavn@nlb.no
    "Talesyntese":
        - incoming-nordic: Fornavn.Etternavn@nlb.no
        # og så videre...
```

Eksempel på regneark:

Produksjonslinje: | innkommende/nordisk | master/EPUB | master/NLBPUB | metadata | utgave-inn/e-bok | …
-- | -- | -- | -- | -- | -- | --
e-bok | ansvarlig: Arne | ansvarlig: Bob |   |   |   |  
100001 | ok | ok | ok | feil |   |  
100002 |   |   |   |   |   |  
100003 |   |   |   |   |   |  
100004 |   |   |   |   |   |  
100005 |   |   |   |   |   |  
100006 |   |   |   |   |   |  
100007 |   |   |   |   |   |  
100008 |   |   |   |   |   |  
100009 |   |   |   |   |   |  
100010 |   |   |   |   |   |  

- Cellene bør inneholde samme info som Slack (en linje med tekst + lenker).
- Bakgrunnsfarge bør gjenspeile status (suksess, advarsel, feil, bok mangler).

Lagres som HTML-filer et eller annet sted under rapport-mappa. Kanskje som `rapporter/produksjonslinjer/e-bok.html` osv.?

Kanskje både mapper og pipelines bør være egne kolonner. Eventuelt så slår vi sammen pipelines med f.eks. etterfølgende mappe, også får den første mappen en egen kolonne. Jeg heller mot første alternativ.
