### ISSUE TITLE
Egen administrator-liste for feilmeldinger

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#94]
I `produksjonssystem.yaml`, legg til en egen seksjon på toppen. For eksempel:

```yaml
common:
  administrators:
    - jostein@nlb.no
    - espen@nlb.no
```

Denne må tolkes som en global konfigurasjon og være tilgjengelig for alle pipelines. Kanskje under `Pipeline.common_config` eller lignende.

Når e-post sendes ut fra `report.py`, bør alle administratorer legges til som mottakere, med mindre e-posten er en "success".
